name: Application PR Workflow

on:
  pull_request:
    branches:
      - '*'

jobs:
    setup_and_trigger_tests:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "$DEV_ENV_FILE" > .env

      - name: Install application dependencies
        run: npm install

      - name: Start application
        run: |
          echo "Starting application..."
          npm start &
          echo "Application started."
          
      - name: Trigger Tests
        run: |
          cd tests
          echo "$TEST_ENV_FILE" > .env 
          npm install
          npm run tests:run:all
            