name: Application PR Workflow

on:
  pull_request:
    branches:
      - '*'

jobs:
    setup_and_trigger_tests:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "$ENV_FILE" > .env

      - name: Install application dependencies
        run: npm install

      - name: Start application
        run: |
          echo "Starting application..."
          npm start &
          echo "Application started."
          
      - name: Trigger Tests
        uses: actions/github-script@v5
        with:
          script: |
            const { Octokit } = require('@octokit/rest');  // Import Octokit
            const token = process.env.GITHUB_TOKEN;
            const owner = 'sashasher24';
            const repo = 'usof_tests';
              
            const octokit = new Octokit({ auth: token });
            await octokit.rest.repos.createDispatchEvent({
              owner,
              repo,
              event_type: 'run_tests',  // Replace with your custom event name
            });

      - name: Wait for Tests to Complete
        run: |
          while true; do
            job_status=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/sashasher24/usof_tests/actions/jobs?event=workflow_run" \
              | jq '.workflow_runs[] | select(.name == "tests_workflow") | .status')
        
            if [[ $job_status == '"completed"' ]]; then
              echo "Tests completed."
              break
            else
              echo "Waiting for tests to complete..."
              sleep 10  # Adjust the sleep interval as needed
            fi
          done
  
      - name: Cleanup
        run: |
          kill $(ps aux | grep 'npm start' | awk '{print $2}')
          rm -rf node_modules