name: Application PR Workflow

on:
  pull_request:
    branches:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        echo "$ENV_FILE" > .env

    - name: Install application dependencies
      run: npm install

    - name: Start application
      run: |
        echo "Starting application..."
        npm start &
        echo "Application started."

  trigger_tests:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Tests
      uses: actions/github-script@v5
      with:
        script: |
          const token = process.env.GITHUB_TOKEN;
          const owner = 'sashasher24';
          const repo = 'usof_tests';
            
          const octokit = new Octokit({ auth: token });
          await octokit.rest.repos.createDispatchEvent({
            owner,
            repo,
            event_type: 'run_tests',  // Replace with your custom event name
          });

#   tests:
#     needs: setup
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout tests repository
#       uses: actions/checkout@v2
#       with:
#         repository: sashasher24/usof_tests
#         ref: main  # Or the branch you want to use
